// Code generated by running "go generate" in golang.org/x/text. DO NOT EDIT.

package translations

import (
	"golang.org/x/text/language"
	"golang.org/x/text/message"
	"golang.org/x/text/message/catalog"
)

type dictionary struct {
	index []uint32
	data  string
}

func (d *dictionary) Lookup(key string) (data string, ok bool) {
	p, ok := messageKeyToIndex[key]
	if !ok {
		return "", false
	}
	start, end := d.index[p], d.index[p+1]
	if start == end {
		return "", false
	}
	return d.data[start:end], true
}

func init() {
	dict := map[string]catalog.Dictionary{
		"en": &dictionary{index: enIndex, data: enData},
		"ru": &dictionary{index: ruIndex, data: ruData},
		"uz": &dictionary{index: uzIndex, data: uzData},
	}
	fallback := language.MustParse("en")
	cat, err := catalog.NewFromMap(dict, catalog.Fallback(fallback))
	if err != nil {
		panic(err)
	}
	message.DefaultCatalog = cat
}

var messageKeyToIndex = map[string]int{
	"Internal server error":   1,
	"Method not allowed":      2,
	"Phone number is invalid": 0,
}

var enIndex = []uint32{ // 4 elements
	0x00000000, 0x00000018, 0x0000002e, 0x00000041,
} // Size: 40 bytes

const enData string = "" + // Size: 65 bytes
	"\x02Phone number is invalid\x02Internal server error\x02Method not allow" +
	"ed"

var ruIndex = []uint32{ // 4 elements
	0x00000000, 0x0000002d, 0x0000005e, 0x0000007f,
} // Size: 40 bytes

const ruData string = "" + // Size: 127 bytes
	"\x02Неверный номер телефона\x02Внутренняя ошибка сервера\x02Метод не раз" +
	"решен"

var uzIndex = []uint32{ // 4 elements
	0x00000000, 0x00000018, 0x00000031, 0x00000047,
} // Size: 40 bytes

const uzData string = "" + // Size: 71 bytes
	"\x02Noto'gri telefon raqami\x02Serverdagi ichki xatolik\x02Usul ruxsat e" +
	"tilmagan"

	// Total table size 383 bytes (0KiB); checksum: 7BB7E306
